[cord]
metadata = "/home/ego/Github/corona_nlp_app/src/CORD-19-research-challenge/2020-03-13/all_sources_metadata_2020-03-13.csv"
source = [ "/home/ego/Github/corona_nlp_app/src/CORD-19-research-challenge/2020-03-13/biorxiv_medrxiv/biorxiv_medrxiv", "/home/ego/Github/corona_nlp_app/src/CORD-19-research-challenge/2020-03-13/noncomm_use_subset/noncomm_use_subset", "/home/ego/Github/corona_nlp_app/src/CORD-19-research-challenge/2020-03-13/comm_use_subset/comm_use_subset", "/home/ego/Github/corona_nlp_app/src/CORD-19-research-challenge/2020-03-13/pmc_custom_license/pmc_custom_license",]

[engine]
model_device = "cpu"
index = "/home/ego/Github/corona_nlp_app/src/data/EMBED_STORE_IVF773_HNSW32_NP4202.bin"
papers = "/home/ego/Github/corona_nlp_app/src/data/STRING_STORE_4202.pkl"

[data]
embeddings = "/home/ego/Github/corona_nlp_app/src/data/EMBED_STORE_4202.npy"

[models]
question_answering = "amoux/scibert_nli_squad"
sentence_transformer = "/home/ego/Github/corona_nlp_app/src/model/scibert-nli"
spacy_nlp = "en_core_sci_sm"

[fastapi]
port = 8080
nprobe = 4

[streamlit]
port = 8084
enable_tts = true
num_papers = 4202
num_sentences = 598839
text_source = "body_text"
subsets = [ "biorxiv_medrxiv", "noncomm_use_subset", "comm_use_subset", "pmc_custom_license",]
dataset_version = "2020-03-13"
qknn_file = "/home/ego/Github/corona_nlp_app/src/QKNN.pkl"

[tts]
port = false
cache_dir = "/home/ego/Github/corona_nlp_app/src/tts_cache"

[cord.init]
index_start = 1
sort_first = true

[tts.init]
apikey = "KimsTEZMLu5TPUmS62utcjbt-ywpu95inG1cvqW43ROL"
disable_ssl = false
url = "https://api.us-south.text-to-speech.watson.cloud.ibm.com/instances/7b0d5686-5cb2-4bad-bc78-796b95de05cc"

[tts.voice]
customizable = true
description = "Kevin: American English male voice. Dnn technology"
gender = "male"
language = "en-US"
name = "en-US_KevinV3Voice"
url = "https://api.us-south.text-to-speech.watson.cloud.ibm.com/instances/7b0d5686-5cb2-4bad-bc78-796b95de05cc/v1/voices/en-US_KevinV3Voice"

[tts.voice.supported_features]
custom_pronuciation = true
voice_transformation = false
