[cord]
version = "2020-03-20"
num_papers = 6641
num_sents = 1003614
index_start = 1
sort_first = true
text_source = "body_text"
subsets = [ "biorxiv_medrxiv", "comm_use_subset", "noncomm_use_subset", "custom_license",]
metadata = "/home/user/.cache/coronanlp/semanticscholar/hr/2020-03-20/metadata.csv"
source = [
    "/home/user/.cache/coronanlp/semanticscholar/hr/2020-03-20/biorxiv_medrxiv",
    "/home/user/.cache/coronanlp/semanticscholar/hr/2020-03-20/comm_use_subset",
    "/home/user/.cache/coronanlp/semanticscholar/hr/2020-03-20/noncomm_use_subset",
    "/home/user/.cache/coronanlp/semanticscholar/hr/2020-03-20/custom_license",
]

[engine]
max_seq_length = 512
do_lower_case = false
model_device = "cuda"

[engine.question_answering]
topk = 5
top_p = 35
nprobe = 128
doc_stride = 1
max_answer_len = 256
max_seq_len = 256
max_question_len = 256
handle_impossible_answer = true

[engine.compressor]
hidden_layer = -2
pooling = "mean"
ratio = 0.3
use_first = true

[models]
sentence_encoder = "amoux/scibert_nli_squad"
question_answering = "amoux/scibert_nli_squad"
spacy_nlp = "en_core_sci_sm"

[stores]
embed = ""
index = ""
sents = ""
is_custom_store = false

[fastapi]
port = 8080

[streamlit]
port = 8084
qknn_file = "corona_nlp_app/src/QKNN.pkl"
enable_tts = false
top_k_params = [3, 9, 5]
top_p_params = [25, 75, 32]
min_valid_words = 4
topic_index = 5

[tts]
cache_dir = "corona_nlp_app/src/tts_cache"
port = false

[tts.init]
apikey = "<TTS-API-KEY>"
disable_ssl = false
url = "<IAM-IBM-TTS-API-URL>"

[tts.voice]
customizable = true
description = "Kevin: American English male voice. Dnn technology"
gender = "male"
language = "en-US"
name = "en-US_KevinV3Voice"
url = "<IAM-IBM-TTS-API>"

[tts.voice.supported_features]
custom_pronuciation = true
voice_transformation = false
