
[cord]
version = "2020-03-13"
num_papers = 4202
num_sents = 598839
index_start = 1
sort_first = true
text_source = "body_text"
subsets = ["biorxiv_medrxiv", "noncomm_use_subset", "comm_use_subset", "pmc_custom_license"]
metadata = "/home/ego/Github/corona_nlp_app/src/CORD-19-research-challenge/2020-03-13/all_sources_metadata_2020-03-13.csv"
source = [
  "/home/ego/Github/corona_nlp_app/src/CORD-19-research-challenge/2020-03-13/biorxiv_medrxiv/biorxiv_medrxiv",
  "/home/ego/Github/corona_nlp_app/src/CORD-19-research-challenge/2020-03-13/noncomm_use_subset/noncomm_use_subset",
  "/home/ego/Github/corona_nlp_app/src/CORD-19-research-challenge/2020-03-13/comm_use_subset/comm_use_subset",
  "/home/ego/Github/corona_nlp_app/src/CORD-19-research-challenge/2020-03-13/pmc_custom_license/pmc_custom_license",
]

[engine]
max_seq_length = 256
do_lower_case = false
model_device = "cpu"
summarizer_hidden = -2
summarizer_reduce = 'mean'
lengths_from_sents = true

[engine.summarizer_kwargs]
ratio = 0.3
use_first = true
algorithm = "kmeans"

[models]
sentence_encoder = "amoux/scibert_nli_squad"
question_answering = "amoux/scibert_nli_squad"
spacy_nlp = "en_core_sci_sm"

[stores]
embed = ""
index = ""
sents = ""
is_custom_store = false

[fastapi]
nprobe = 4
port = 8080

[streamlit]
qknn_file = "/home/ego/Github/corona_nlp_app/src/QKNN.pkl"
enable_tts = true
port = 8084

[tts]
cache_dir = "/home/ego/Github/corona_nlp_app/src/tts_cache"
port = false

[tts.init]
apikey = "KimsTEZMLu5TPUmS62utcjbt-ywpu95inG1cvqW43ROL"
disable_ssl = false
url = "https://api.us-south.text-to-speech.watson.cloud.ibm.com/instances/7b0d5686-5cb2-4bad-bc78-796b95de05cc"

[tts.voice]
customizable = true
description = "Kevin: American English male voice. Dnn technology"
gender = "male"
language = "en-US"
name = "en-US_KevinV3Voice"
url = "https://api.us-south.text-to-speech.watson.cloud.ibm.com/instances/7b0d5686-5cb2-4bad-bc78-796b95de05cc/v1/voices/en-US_KevinV3Voice"

[tts.voice.supported_features]
custom_pronuciation = true
voice_transformation = false
