[stores]
embed = "devtest"
index = "devtest"
sents = "devtest"

[cord]
metadata = "/home/ego/.cache/coronanlp/semanticscholar/hr/2020-03-20/metadata.csv"
source = [
  "/home/ego/.cache/coronanlp/semanticscholar/hr/2020-03-20/biorxiv_medrxiv",
  "/home/ego/.cache/coronanlp/semanticscholar/hr/2020-03-20/comm_use_subset",
  "/home/ego/.cache/coronanlp/semanticscholar/hr/2020-03-20/noncomm_use_subset",
  "/home/ego/.cache/coronanlp/semanticscholar/hr/2020-03-20/custom_license",
]

[engine]
index = "devtest"
model_device = "cpu"
papers = nan
sents = "devtest"

[data]
embed = "devtest"
embeddings = nan

[models]
encoder = "amoux/scibert_nli_squad"
question_answering = "amoux/scibert_nli_squad"
spacy_nlp = "en_core_sci_sm"

[fastapi]
nprobe = 4
port = 8080

[streamlit]
dataset_version = "2020-03-20"
enable_tts = true
num_papers = 1000
num_sentences = 155748
port = 8084
qknn_file = "/home/ego/Github/corona_nlp_app/src/QKNN.pkl"
subsets = ["biorxiv_medrxiv", "comm_use_subset", "noncomm_use_subset", "custom_license"]
text_source = "body_text"

[tts]
cache_dir = "/home/ego/Github/corona_nlp_app/src/tts_cache"
port = false

[cord.init]
index_start = 1
sort_first = true

[tts.init]
apikey = "KimsTEZMLu5TPUmS62utcjbt-ywpu95inG1cvqW43ROL"
disable_ssl = false
url = "https://api.us-south.text-to-speech.watson.cloud.ibm.com/instances/7b0d5686-5cb2-4bad-bc78-796b95de05cc"

[tts.voice]
customizable = true
description = "Kevin: American English male voice. Dnn technology"
gender = "male"
language = "en-US"
name = "en-US_KevinV3Voice"
url = "https://api.us-south.text-to-speech.watson.cloud.ibm.com/instances/7b0d5686-5cb2-4bad-bc78-796b95de05cc/v1/voices/en-US_KevinV3Voice"

[tts.voice.supported_features]
custom_pronuciation = true
voice_transformation = false
